---
name: test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: suzuki-shunsuke/aqua-installer@main
        with:
          version: v0.4.0-2
      - run: aqua i --test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
